project:
  type: website
  output-dir: docs

website:
  title: Rui Wang
  navbar:
    right:
      - href: index.qmd
        text: About
      - href: pages/publications.qmd
        text: Publications
      - href: pages/teaching.qmd
        text: Teaching
      - text: CV/Resume
        href: files/CV_new.pdf



format:
  html:
     theme:
      light: flatly
      dark: darkly
     css: styles/styles.css
     toc: true
     toc_depth: 3
     toc_float: true
     toc_smooth_scroll: true
     toc_highlight: true
     fig-align: center

editor: source
